# ------------------------------------------------------------
# Phase 1 — Node Contract Validation
# ------------------------------------------------------------
- import_tasks: phase1_checks.yml

# ------------------------------------------------------------
# Phase 2 — Kubernetes Validation
# ------------------------------------------------------------
- import_tasks: phase2_checks.yml
  when: inventory_hostname in groups[control_plane_group]

# ------------------------------------------------------------
# Phase 3 — Vault Validation
# ------------------------------------------------------------
- import_tasks: phase3_checks.yml
  when: inventory_hostname in groups[control_plane_group]
# ------------------------------------------------------------
# Phase 4 — Platform Application Services
# ------------------------------------------------------------
- import_tasks: PAS_checks.yml
  when: inventory_hostname in groups[control_plane_group]
