- name: 'Install Helm Dependencies'
  package:
    name:
      - curl
      - gpg
      - apt-transport-https
    state: present
    update_cache: yes

- name: 'Helm GPG Key, Ensure keyrings directory exists'
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: 'Download Helm repo GPG Key'
  get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey 
    dest: /tmp/helm.gpg
    mode: '0644'

- name: 'Convert Helm GPG key to dearmored format'
  command: >
    gpg --dearmor --yes
    -o /usr/share/keyrings/helm.gpg
    /tmp/helm.gpg
  args:
    creates: /usr/share/keyrings/helm.gpg

- name: 'Remove Temporary Helm file'
  file:
    path: /tmp/helm.gpg
    state: absent

- name: 'Add Helm repository'
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
    filename: helm
    state: present

- name: 'Install Helm'
  package:
    name: helm
    state: present
    update_cache: yes

- name: 'Check Helm Version'
  command: 'helm version --short'
  register: helm_vesion
  changed_when: false

- name: Hold Helm package
  dpkg_selections:
    name: helm
    selection: hold
