- block:

    - import_tasks: install_helm.yml
    - import_tasks: add_repo.yml
    - import_tasks: create_namespace.yml
    - import_tasks: deploy_vault.yml
    - import_tasks: wait_vault.yml
    - import_tasks: init_vault.yml
    - import_tasks: unseal_vault.yml

  when: inventory_hostname in groups[control_plane_group]