---
galaxy_info:
  role_name: vault
  author: Mohammed <YourLastName>
  description: Deploys and validates HashiCorp Vault inside Kubernetes.
  company: ""
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - vault
    - hashicorp
    - secrets
    - kubernetes
    - security

dependencies:
  - kubernetes