min_cpu: 2
min_memory_mb: 3096

required_kernel_modules:
  - overlay
  - br_netfilter

sysctl_params:
  net.ipv4.ip_forward: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1


