vault_namespace: "vault"
vault_release_name: "vault"
vault_chart_version: "0.32.0"
vault_image_tag: "1.21.2"


vault_helm_repo_name: "hashicorp"
vault_helm_repo_url: "https://helm.releases.hashicorp.com"

vault_storage_size: "500Mi"
vault_replicas: 2

kubeconfig_path: "/etc/kubernetes/admin.conf"
