- name: 'Disable swap'
  command: 'swapoff -a'
  when: ansible_swaptotal_mb | int > 0

- name: 'remove swap from /etc/fstab'
  replace:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    replace: '' 

