k8s_version: "v1.34"
init_k8s_version: "1.34.0"
pod_network_cidr: "192.168.0.0/16"

k8s_apt_key_url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key"
k8s_apt_repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/ /"
k8s_keyring_path: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"

kube_admin_conf: "/etc/kubernetes/admin.conf"
kubelet_conf: "/etc/kubernetes/kubelet.conf"
