# ------------------------------------------------------------
# Groups
# ------------------------------------------------------------

control_plane_group: "_control_plane"
worker_group: "_workers"

# ------------------------------------------------------------
# Kubernetes
# ------------------------------------------------------------
kube_version: "1.34.0"
pod_network_cidr: "192.168.0.0/16"
kubeconfig_path: "/etc/kubernetes/admin.conf"

# ------------------------------------------------------------
# Vault
# ------------------------------------------------------------
vault_namespace: "vault"
vault_release_name: "vault"
vault_chart_version: "0.32.0"
vault_helm_repo_name: "hashicorp"
vault_helm_repo_url: "https://helm.releases.hashicorp.com"
