- name: Generate join command
  command: >
    kubeadm token create
    --print-join-command
    --kubeconfig {{ kube_admin_conf }}
  register: join_command_result
  changed_when: false


- name: 'Set join command fact'
  set_fact:
    join_command: "{{ join_command_result.stdout }}"